const ProductList = [
  {
    id: 1,
    name: 'Nadia Camel Accent Chair',
    price: '49.00$',
    image: '/shopImage/noithat1.jpg',
    description: 'Stylish, stylish form',
  },
  {
    id: 2,
    name: 'EL TIEMPO Lounge chair',
    price: '89.00$',
    image: '/shopImage/noithat2.jpg',
    description: 'Brushed velvet design, ultra-modern',
  },
  {
    id: 3,
    name: 'Wood Sideboard Shelf',
    price: '158.00$',
    image: '/shopImage/noithat3.jpg',
    description: '2-Door Solid Wood Display Slide',
  },
  {
    id: 4,
    name: 'Seb Bar Cabinet',
    price: '98.00$',
    image: '/shopImage/noithat4.jpg',
    description: 'Solid-wood Panel frame',
  },
  {
    id: 5,
    name: 'Dark wood accent furniture',
    price: '89.00$',
    image: '/shopImage/noithat5.jpg',
    description: 'Minimalist black accent from dark shelf',
  },
  {
    id: 6,
    name: 'Oval Dining Table',
    price: '99.00$',
    image: '/shopImage/noithat6.jpg',
    description: 'Bright Spacious Surface',
  },
  {
    id: 7,
    name: 'Velvet Pull-Out Sofa Bed',
    price: '139.00$',
    image: '/shopImage/noithat7.jpg',
    description: 'Orange velvet modern convertible',
  },
  {
    id: 8,
    name: 'Laurent Bouclé Bed',
    price: '49.00$',
    image: '/shopImage/noithat8.jpg',
    description: 'Classic queen-sized, warm atmosphere',
  },
  {
    id: 9,
    name: 'Abster Coffee Table',
    price: '59.00$',
    image: '/shopImage/noithat9.jpg',
    description: 'Classic design and modern charm',
  },
  {
    id: 10,
    name: 'Accent Chair',
    price: '99.00$',
    image: '/shopImage/noithat10.jpg',
    description: 'Curved green style',
  },
  {
    id: 11,
    name: 'Fluted Side Table',
    price: '189.00$',
    image: '/shopImage/noithat11.jpg',
    description: 'Rounded wooden side piece',
  },
  {
    id: 12,
    name: 'Sideboard',
    price: '49.00$',
    image: '/shopImage/noithat12.jpg',
    description: 'Black wooden cabinet with glass',
  },
  {
    id: 13,
    name: 'Crescent Leather Sofa',
    price: '159.00$',
    image: '/shopImage/noithat13.jpg',
    description: 'Premium leather, crescent shape',
  },
  {
    id: 14,
    name: 'Retro Reading Lamp',
    price: '29.00$',
    image: '/shopImage/noithat14.jpg',
    description: 'Classic retro-style desk lamp',
  },
  {
    id: 15,
    name: 'Glass Vase Trio',
    price: '19.00$',
    image: '/shopImage/noithat1.jpg',
    description: 'Modern minimalist vase set',
  },
  {
    id: 16,
    name: 'Luxury Fabric Bed',
    price: '179.00$',
    image: '/shopImage/noithat2.jpg',
    description: 'King-size with layered texture',
  },
  {
    id: 17,
    name: 'Fur Ottoman',
    price: '39.00$',
    image: '/shopImage/noithat3.jpg',
    description: 'Cozy furry footstool',
  },
  {
    id: 18,
    name: 'Abstract Art Painting',
    price: '89.00$',
    image: '/shopImage/noithat4.jpg',
    description: 'Bold and vibrant colors',
  },
  {
    id: 19,
    name: 'Gold Standing Mirror',
    price: '129.00$',
    image: '/shopImage/noithat5.jpg',
    description: 'Elegant frame, full-length',
  },
  {
    id: 20,
    name: 'Indoor Plant Decor',
    price: '24.00$',
    image: '/shopImage/noithat6.jpg',
    description: 'Lush green artificial plant',
  },
];

export default ProductList;
